name: Deep Sea Games Studio
favicon: null
layout_spectrum: 0.84655
typography_spectrum: 1
title: Deep Sea Games Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4fc3f7'
    - '#0477bd'
    - '#04a9f4'
    - '#03579b'
    - '#b3e4fb'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
